### ISSUE TITLE
This plugin will be used with any addons of Elementor

### ISSUE THREAD

**Issue by posimyth** [FreshyMichael/elementor-plus-addons-error-corrections#1]
Hello @FreshyMichael 

We are glad to see you made this code. Though, It's just single line of CSS, But It is quite useful to many. 

We need to clarify here that, This can be helpful to each addons of elementor as this is memory limit issue. This memory limit issue arise, When there are low server memory and lots of widgets enabled. 

Solution 1 : Increase memory limit.
Solution 2 : Disable all unused widgets from all the addons you are using. (Hope Elementor will give that option for their FREE and PRO version soon to disable widgets.)
Solution 3 : This code you created. That will simply disable that loader. (Elementor might added this loader to avoid higher memory limit usage(and that might leads to downtime) in servers especially cloud servers.)

Hope above information will be useful.

**Comment by maldersIO** [comment]
Greetings @posimyth, 

Thanks so much for reaching out. Yes, we're keenly aware of the long term solutions to Elementor Memory Limit Issues. This plugin patch, which is indeed a single line of CSS, is meant only as a temporary workaround, until the number of addons are decreased, or memory limits are increased (which is not possible in all server environments) .

By disabling the loading overlay, this at least allows for temporary edits to pages, that are being blocked by the loader failing to complete. 

Thanks so much!
